linters-settings:
  dupl:
    threshold: 100
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "ioutil is deprecated starting with Go 1.16"
  funlen:
    lines: 320
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 8
  gomnd:
  govet:
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    # bodyclose
    - contextcheck
    #    - cyclop
    - depguard
    - dogsled
    #    - dupl
    - durationcheck
    - errcheck
    #    - errname
    #    - errorlint
    #    - exhaustive
    #    - exhaustivestruct
    # - exportloopref -> copyloopvar # but we are using go 1.18 
    #    - forbidigo
    #    - forcetypeassert
    - funlen
    #    - gci
    #    - gochecknoglobals
    #    - gochecknoinits
    #    - gocognit
    - goconst
    #    - gocritic
    #    - gocyclo
    #    - godot
    #    - godox
    #    - goerr113
    # gofmt
    #    - gofumpt
    - goheader
    - goimports
    #    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    #    - gosec
    - gosimple
    - govet
    #    - ifshort
    - importas
    - ineffassign
    #    - ireturn
    #    - lll
    # - copyloopvar # we have go 1.18
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    #    - nilnil
    #    - nlreturn
    # noctx
    #    - nolintlint
    #    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
      #- rowserrcheck
      #- sqlclosecheck
    - staticcheck
    - stylecheck
    #    - tagliatelle
    - usetesting
    #    - testpackage
    #    - thelper
    - tparallel
    # typecheck
    - unconvert
    - unparam
    #    - unused
    #    - varnamelen
    #- wastedassign
    #    - whitespace
    #    - wrapcheck
    #    - wsl

issues:
  exclude-rules:
    - path: (.*)_test\.go
      linters:
        - funlen
        - goconst
        - gosimple
    - path: /
      linters:
      - typecheck
run:
service:
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
